# Generated by Django 5.0.6 on 2026-03-24 00:48

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_category_options_alter_order_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="size_code",
            field=models.CharField(blank=True, default="", max_length=1),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="size_label",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.CreateModel(
            name="ProductSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size_code",
                    models.CharField(
                        choices=[("S", "Small"), ("M", "Medium"), ("L", "Large")],
                        max_length=1,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("stock", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "ordering": ["size_code"],
                "unique_together": {("product", "size_code")},
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="store.productsize",
            ),
        ),
    ]
