# Generated by Django 5.0.6 on 2026-03-25 04:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_orderitem_size_code_orderitem_size_label_productsize_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsize",
            options={"ordering": ["sort_order", "id"]},
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="size_label",
            new_name="option_dimensions",
        ),
        migrations.AlterUniqueTogether(
            name="productsize",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="size_code",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="option_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="productsize",
            name="dimensions_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional display text, e.g. '30 x 40 cm' or 'Approx 42 x 60 cm'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="edition_sold",
            field=models.PositiveIntegerField(
                default=0, help_text="How many of this print option have sold."
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="edition_total",
            field=models.PositiveIntegerField(
                blank=True, help_text="Optional total edition size, e.g. 50.", null=True
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="height_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Customer-facing option name, e.g. 'Standard Print', 'Framed Print', 'Large Edition'.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="sort_order",
            field=models.PositiveIntegerField(
                default=0, help_text="Lower numbers show first."
            ),
        ),
        migrations.AddField(
            model_name="productsize",
            name="width_cm",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Fallback/base price. Product print options can override this.",
                max_digits=10,
            ),
        ),
        migrations.AlterField(
            model_name="productsize",
            name="stock",
            field=models.PositiveIntegerField(
                default=0, help_text="Current available stock for this print option."
            ),
        ),
        migrations.RemoveField(
            model_name="productsize",
            name="label",
        ),
        migrations.RemoveField(
            model_name="productsize",
            name="size_code",
        ),
    ]
