# Generated by Django 5.0.6 on 2024-07-31 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_remove_post_featured_image_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='artwork',
            name='artwork_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='artwork_image'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='post_image'),
        ),
    ]
