# Generated by Django 6.0.1 on 2026-03-04 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0007_remove_artwork_image_remove_post_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingListSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                ("source", models.CharField(blank=True, max_length=120)),
            ],
        ),
    ]
